export const INITIAL_STUDENT_DATA: Record<string, { name: string; period: string; feedback: string; role?: string }> = {
    // Instructor
    "AMJH051586": { name: "Instructor (Andrew Hogan)", period: "N/A", feedback: "Instructor access granted. All systems operational.", role: "instructor" },

    // 2nd Period
    "ACQ012612": { name: "Angelique C. Quintana-Galindo", period: "2nd", feedback: "Pending feedback for Assignment 1." },
    "EEB042012": { name: "Emery E. Burns", period: "2nd", feedback: "Pending feedback for Assignment 1." },
    "GIL063012": { name: "Gavin I. Luna", period: "2nd", feedback: "Pending feedback for Assignment 1." },
    "HMH032612": { name: "Haven M. Herr", period: "2nd", feedback: "Pending feedback for Assignment 1." },
    "JLM112211": { name: "Jada L. Munoz", period: "2nd", feedback: "Pending feedback for Assignment 1." },
    "KNC011912": { name: "Kaylee N. Camper", period: "2nd", feedback: "Pending feedback for Assignment 1." },
    "KRM080911": { name: "Kendall R. Meirowsky", period: "2nd", feedback: "Pending feedback for Assignment 1." },
    "MRJ070211": { name: "Maxwell R. Johnson", period: "2nd", feedback: "Pending feedback for Assignment 1." },
    "NSH071912": { name: "Nicholas S. Henderson JR", period: "2nd", feedback: "Pending feedback for Assignment 1." },
    "NRS101811": { name: "Nolan R. Stone", period: "2nd", feedback: "Pending feedback for Assignment 1." },
    "PJS082312": { name: "Peter J. Schreiner", period: "2nd", feedback: "Pending feedback for Assignment 1." },
    "RDI090511": { name: "Ryan D. Isaacs", period: "2nd", feedback: "Pending feedback for Assignment 1." },
    "RJJ031612": { name: "Ryder J. Jakubov", period: "2nd", feedback: "Pending feedback for Assignment 1." },

    // 3rd Period
    "AEP091011": { name: "Alexander E. Purcell", period: "3rd", feedback: "Pending feedback for Assignment 1." },
    "ATM020312": { name: "Ashton T. Manzoor", period: "3rd", feedback: "Pending feedback for Assignment 1." },
    "BMZ012312": { name: "Boston M. Zimmerman", period: "3rd", feedback: "Pending feedback for Assignment 1." },
    "BPU092911": { name: "Brittany P. Urzua-Moreno", period: "3rd", feedback: "Pending feedback for Assignment 1." },
    "BEB050412": { name: "Bronwyn E. Bunn", period: "3rd", feedback: "Pending feedback for Assignment 1." },
    "BHB071112": { name: "Bryson H. Bauer", period: "3rd", feedback: "Pending feedback for Assignment 1." },
    "DKB091011": { name: "Daxton K. Breen", period: "3rd", feedback: "Pending feedback for Assignment 1." },
    "ETH102111": { name: "Emilee T. Hendry", period: "3rd", feedback: "Pending feedback for Assignment 1." },
    "ELL050312": { name: "Emma L. Lawrence", period: "3rd", feedback: "Pending feedback for Assignment 1." },
    "GIC041712": { name: "Gabriel I. Cordova", period: "3rd", feedback: "Pending feedback for Assignment 1." },
    "HEA110811": { name: "Harper E. Adams", period: "3rd", feedback: "Pending feedback for Assignment 1." },
    "IMG121411": { name: "Isabella M. Garcia", period: "3rd", feedback: "Pending feedback for Assignment 1." },
    "KAO010411": { name: "Kylie A. Olguin", period: "3rd", feedback: "Pending feedback for Assignment 1." },
    "LMH081111": { name: "Layna M. Harper", period: "3rd", feedback: "Pending feedback for Assignment 1." },
    "LIC021712": { name: "Luke I. Cox JR", period: "3rd", feedback: "Pending feedback for Assignment 1." },
    "MLC020612": { name: "Marie L. Clement", period: "3rd", feedback: "Pending feedback for Assignment 1." },
    "NAT080511": { name: "Nicholas A. Tabtab", period: "3rd", feedback: "Pending feedback for Assignment 1." },
    "OJB011112": { name: "Olivia J. Bollenbach", period: "3rd", feedback: "Pending feedback for Assignment 1." },
    "RCC073111": { name: "Rosemary C. Carter", period: "3rd", feedback: "Pending feedback for Assignment 1." },
    "SCH022312": { name: "Samantha C. Holeman", period: "3rd", feedback: "Pending feedback for Assignment 1." },

    // 4th Period
    "ARG092611": { name: "Ava R. Gould", period: "4th", feedback: "Pending feedback for Assignment 1." },
    "ARM060112": { name: "Ayla R. Mills", period: "4th", feedback: "Pending feedback for Assignment 1." },
    "BNB011512": { name: "Brooklyn N. Best", period: "4th", feedback: "Pending feedback for Assignment 1." },
    "CKV020512": { name: "Cecilia K. Vo", period: "4th", feedback: "Pending feedback for Assignment 1." },
    "DSL082111": { name: "Daniel S. Laochinda", period: "4th", feedback: "Pending feedback for Assignment 1." },
    "DCP121311": { name: "Dylan C. Pace", period: "4th", feedback: "Pending feedback for Assignment 1." },
    "EAN053012": { name: "Elijah A. Nading", period: "4th", feedback: "Pending feedback for Assignment 1." },
    "JRU072212": { name: "Jaydin R. Urbina", period: "4th", feedback: "Pending feedback for Assignment 1." },
    "JI090911":  { name: "Joakim Ibarra", period: "4th", feedback: "Pending feedback for Assignment 1." },
    "JRD030912": { name: "Joanna R. DeWitt", period: "4th", feedback: "Pending feedback for Assignment 1." },
    "JAS061412": { name: "Joel A. Schmitz", period: "4th", feedback: "Pending feedback for Assignment 1." },
    "KSK031512": { name: "Kathryn S. Kennedy", period: "4th", feedback: "Pending feedback for Assignment 1." },
    "KSP072511": { name: "Kyndal S. Percival", period: "4th", feedback: "Pending feedback for Assignment 1." },
    "MGS080712": { name: "Makenzie G. Sell", period: "4th", feedback: "Pending feedback for Assignment 1." },
    "MAA090511": { name: "Miriam A. Alhameedawi", period: "4th", feedback: "Pending feedback for Assignment 1." },
    "RLS040712": { name: "Reagan L. Schon", period: "4th", feedback: "Pending feedback for Assignment 1." },
    "RAT021812": { name: "Roger A. Taylor JR", period: "4th", feedback: "Pending feedback for Assignment 1." },
    "SNG082911": { name: "Serynity N. Gray", period: "4th", feedback: "Pending feedback for Assignment 1." },
    "TDH041712": { name: "Tristynn D. Harding", period: "4th", feedback: "Pending feedback for Assignment 1." },
    "WWB062112": { name: "Weston W. Beevers", period: "4th", feedback: "Pending feedback for Assignment 1." },
    "XLH032612": { name: "Xia L. Hicks", period: "4th", feedback: "Pending feedback for Assignment 1." },

    // 5th Period
    "ARW112411": { name: "Adelyn R. Wiebe", period: "5th", feedback: "Pending feedback for Assignment 1." },
    "AMM080612": { name: "Alysia M. Montano", period: "5th", feedback: "Pending feedback for Assignment 1." },
    "AAS020912": { name: "Avery A. Stivers", period: "5th", feedback: "Pending feedback for Assignment 1." },
    "BMM010312": { name: "Bristol M. Morales", period: "5th", feedback: "Pending feedback for Assignment 1." },
    "CPG060811": { name: "Christian P. Garcia", period: "5th", feedback: "Pending feedback for Assignment 1." },
    "EMW030812": { name: "Easton M. Womack", period: "5th", feedback: "Pending feedback for Assignment 1." },
    "EVH100411": { name: "Eden V. Howerton", period: "5th", feedback: "Pending feedback for Assignment 1." },
    "GMG052412": { name: "Gabriel M. Graham", period: "5th", feedback: "Pending feedback for Assignment 1." },
    "GN072212":  { name: "Gisselle Nevarez Amaya", period: "5th", feedback: "Pending feedback for Assignment 1." },
    "HEN092011": { name: "Harper E. Neth", period: "5th", feedback: "Pending feedback for Assignment 1." },
    "HJT110111": { name: "Hayden J. Terhune", period: "5th", feedback: "Pending feedback for Assignment 1." },
    "HOV062112": { name: "Henry O. Van Tassell", period: "5th", feedback: "Pending feedback for Assignment 1." },
    "IGC013112": { name: "Isabella G. Cooley", period: "5th", feedback: "Pending feedback for Assignment 1." },
    "JAM080112": { name: "Jackson A. Miller", period: "5th", feedback: "Pending feedback for Assignment 1." },
    "MAD012412": { name: "Miguel A. Dorantes JR", period: "5th", feedback: "Pending feedback for Assignment 1." },
    "OGH092411": { name: "Olivia G. Hanson", period: "5th", feedback: "Pending feedback for Assignment 1." },
    "RLB020212": { name: "Ruby L. Brown", period: "5th", feedback: "Pending feedback for Assignment 1." },
    "SAS012012": { name: "Steven A. Sampson", period: "5th", feedback: "Pending feedback for Assignment 1." },
    "TAV071312": { name: "Timauria A. Vaughn-Collins", period: "5th", feedback: "Pending feedback for Assignment 1." },
    "VPN052212": { name: "Van P. Nguyen", period: "5th", feedback: "Pending feedback for Assignment 1." },
    "WAY062111": { name: "William A. Youngers", period: "5th", feedback: "Pending feedback for Assignment 1." }
};
